# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Good times are always short. # ex. I m Chuan
name: LeisureBo # ex. DONGChuan
email: w.47@qq.com
# location: China # ex. Nice, France
# company: company
# company_url: none
description: personal blog
encoding: "utf-8"
favicon: favicon.png # Image must be in assets/images

# github_url: https://github.com/leisurebo # ex. https://github.com/DONGChuan
# github_username: LeisureBo # ex. DONGChuan
repository: leisurebo/leisurebo.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://www.itbo.top

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]

# Comments plugins
comments:
  disqus: false
  disqus_url: 'https://leisurebo.disqus.com/embed.js'

  gitalk: true
  gitalk_client_id: 'cac766fc13c6143dbcd6'
  gitalk_secret: 'a05f1b5385bfa6eb1f96d3a1e71f01d033553118'
  gitalk_repo: 'leisurebo.github.io'
  gitalk_owner: 'leisurebo'
  gitalk_admin: 'leisurebo'
  distraction_free_mode: true



